{{- if .Values.alerts.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cueo-alerts
  name: cueo-alerts
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    app: cueo-alerts
status:
  loadBalancer: {}
{{- end }}
