apiVersion: v1
kind: Service
metadata:
  labels:
    app: cueo-frontend
  name: cueo-frontend
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: cueo-frontend
status:
  loadBalancer: {}
