apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cueo-frontend
  name: cueo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cueo-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cueo-frontend
    spec:
      containers:
        - image: {{ .Values.image.repository }}/cue-observe-frontend:{{ .Values.image.tag }}
          name: cueo-frontend
          args:
            - bash
            - -c
            - ./etc/nginx/conf.d/nginx-entrypoint.sh && nginx -g 'daemon off;'
          ports: 
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef: 
                name: cueo-custom
      restartPolicy: Always

