apiVersion: v1
kind: Service
metadata:
  labels:
    app: cueo-redis
  name: cueo-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: cueo-redis
status:
  loadBalancer: {}
