apiVersion: v1
kind: Service
metadata:
  labels:
    app: cueo-backend
  name: cueo-backend
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: cueo-backend
status:
  loadBalancer: {}
