# Generated by Django 3.2.1 on 2021-06-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionparam',
            old_name='paramName',
            new_name='name',
        ),
    ]
