# Generated by Django 3.2.1 on 2021-06-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='dimensions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='granularity',
            field=models.CharField(default='day', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='metrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='timestampColumn',
            field=models.CharField(default='timestamp', max_length=500),
            preserve_default=False,
        ),
    ]
