# Generated by Django 3.2.1 on 2021-07-01 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0002_auto_20210629_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.TextField(blank=True, null=True)),
                ('dimension', models.TextField(blank=True, null=True)),
                ('highOrLow', models.TextField(blank=True, null=True)),
                ('top', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomaly.dataset')),
            ],
        ),
    ]
