# Generated by Django 3.2.1 on 2021-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0002_rename_paramname_connectionparam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionparam',
            name='file',
            field=models.JSONField(default=dict),
        ),
    ]
