# Generated by Django 3.2.1 on 2021-06-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0003_connectionparam_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='title',
            new_name='name',
        ),
    ]
