# Generated by Django 3.2.1 on 2021-07-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0003_anomalydefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateName', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('bodyText', models.TextField(blank=True, null=True)),
                ('supportedVariables', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='anomalydefinition',
            name='top',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensionVal', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('anomalyDefinition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomaly.anomalydefinition')),
            ],
        ),
    ]
