# Generated by Django 3.2.1 on 2021-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0004_auto_20210705_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionparam',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
