# Generated by Django 3.2.1 on 2021-06-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0004_rename_title_connection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionparam',
            name='file',
        ),
        migrations.AddField(
            model_name='connection',
            name='file',
            field=models.JSONField(default=dict),
        ),
    ]
