# Generated by Django 3.2.1 on 2021-07-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0005_alter_connectionparam_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='file',
        ),
        migrations.RemoveField(
            model_name='connectionparam',
            name='file',
        ),
    ]
