# Generated by Django 3.2.1 on 2021-07-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_auto_20210625_0725'),
        ('anomaly', '0006_auto_20210708_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSchedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.crontabschedule')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
    ]
