# Generated by Django 3.2.1 on 2021-07-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('anomaly', '0007_customschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydefinition',
            name='periodicTask',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
