# Generated by Django 3.2.1 on 2021-07-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0008_anomalydefinition_periodictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTimestamp', models.DateTimeField(auto_now_add=True)),
                ('endTimestamp', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(max_length=20)),
                ('runType', models.CharField(blank=True, max_length=20, null=True)),
                ('anomalyDefinition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomaly.anomalydefinition')),
            ],
        ),
    ]
