# Generated by Django 3.2.1 on 2021-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0009_runstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstatus',
            name='logs',
            field=models.JSONField(default=dict),
        ),
    ]
