# Generated by Django 3.2.5 on 2021-07-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0011_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
