# Generated by Django 3.2.5 on 2021-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0013_anomaly_latestrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalydefinition',
            name='top',
        ),
        migrations.AddField(
            model_name='anomalydefinition',
            name='operation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='anomalydefinition',
            name='value',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
