# Generated by Django 3.2.5 on 2021-08-02 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0013_anomaly_latestrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCauseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTimestamp', models.DateTimeField(auto_now_add=True)),
                ('endTimestamp', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(max_length=20)),
                ('logs', models.JSONField(default=dict)),
                ('anomaly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anomaly.anomaly')),
            ],
        ),
        migrations.CreateModel(
            name='RCAAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=500)),
                ('dimensionValue', models.TextField(blank=True, null=True)),
                ('anomalyDate', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomaly.anomaly')),
            ],
        ),
    ]
