# Generated by Django 3.2.5 on 2021-08-06 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0014_auto_20210730_0718'),
        ('anomaly', '0014_rcaanomaly_rootcauseanalysis'),
    ]

    operations = [
    ]
