# Generated by Django 3.2.1 on 2021-08-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0014_auto_20210729_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrule',
            name='detectionRuleType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anomaly.detectionruletype'),
            preserve_default=False,
        ),
    ]
