# Generated by Django 3.2.1 on 2021-08-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0014_auto_20210730_0718'),
        ('anomaly', '0015_detectionrule_detectionruletype'),
    ]

    operations = [
    ]
