# Generated by Django 3.2.1 on 2021-08-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0015_merge_20210806_0248'),
        ('anomaly', '0016_merge_20210806_1138'),
    ]

    operations = [
    ]
