# Generated by Django 3.2.5 on 2021-12-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0019_dataset_isnonrollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installationId', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('databaseType', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
