"""empty message

Revision ID: 35b20eba8d11
Revises: dee2800abe2f
Create Date: 2021-10-29 08:56:02.757378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b20eba8d11'
down_revision = 'dee2800abe2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_card_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('templateName', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('bodyText', sa.String(), nullable=True),
    sa.Column('sql', sa.String(), nullable=True),
    sa.Column('supportedVariables', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_card_template')
    # ### end Alembic commands ###
