"""empty message

Revision ID: 5ad7c63568b1
Revises: 
Create Date: 2021-10-08 08:17:08.223372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad7c63568b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globaldimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('globaldimensionvalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasetId', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('globalDimensionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['globalDimensionId'], ['globaldimension.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('globaldimensionvalues')
    op.drop_table('globaldimension')
    # ### end Alembic commands ###
