"""empty message

Revision ID: dee2800abe2f
Revises: 123a7600c333
Create Date: 2021-10-13 07:41:23.027988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee2800abe2f'
down_revision = '123a7600c333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('global_dimension_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasetId', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('globalDimensionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['globalDimensionId'], ['global_dimension.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('globaldimensionvalues')
    op.drop_table('globaldimension')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globaldimension',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('globaldimension_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='globaldimension_pkey'),
    sa.UniqueConstraint('name', name='globaldimension_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('globaldimensionvalues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datasetId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('globalDimensionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['globalDimensionId'], ['globaldimension.id'], name='globaldimensionvalues_globalDimensionId_fkey'),
    sa.PrimaryKeyConstraint('id', name='globaldimensionvalues_pkey')
    )
    op.drop_table('global_dimension_values')
    op.drop_table('global_dimension')
    # ### end Alembic commands ###
